/* ============================================================
   LearnFlow – All Mock Data
   js/data.js
   ============================================================ */

'use strict';

// ═══════════════════════════════════════════════════════
// DOMAINS
// ═══════════════════════════════════════════════════════
const DOMAINS = [
  { id: 'webdev',     name: 'Web Dev',         emoji: '🌐', count: 248 },
  { id: 'datascience',name: 'Data Science',    emoji: '📊', count: 186 },
  { id: 'design',     name: 'UI/UX Design',    emoji: '🎨', count: 134 },
  { id: 'mobile',     name: 'Mobile Dev',      emoji: '📱', count: 112 },
  { id: 'devops',     name: 'DevOps & Cloud',  emoji: '☁️',  count: 98  },
  { id: 'ai',         name: 'AI & ML',         emoji: '🤖', count: 164 },
  { id: 'business',   name: 'Business',        emoji: '💼', count: 89  },
  { id: 'cybersec',   name: 'Cyber Security',  emoji: '🔐', count: 76  },
];

// ═══════════════════════════════════════════════════════
// COURSES
// ═══════════════════════════════════════════════════════
const COURSES = [
  {
    id: 'c1',
    title: 'React 19 & Next.js 15 — The Complete Guide',
    instructor: 'Priya Sharma',
    domain: 'webdev',
    domainLabel: 'Web Dev',
    emoji: '⚛️',
    level: 'intermediate',
    rating: 4.9,
    reviews: 12480,
    students: '84K',
    duration: '42h',
    price: 1299,
    originalPrice: 4999,
    badge: 'bestseller',
    tags: ['React', 'Next.js', 'TypeScript'],
  },
  {
    id: 'c2',
    title: 'Python for Data Science & Machine Learning Bootcamp',
    instructor: 'Arjun Mehta',
    domain: 'datascience',
    domainLabel: 'Data Science',
    emoji: '🐍',
    level: 'beginner',
    rating: 4.8,
    reviews: 9210,
    students: '120K',
    duration: '55h',
    price: 999,
    originalPrice: 3999,
    badge: 'bestseller',
    tags: ['Python', 'Pandas', 'scikit-learn'],
  },
  {
    id: 'c3',
    title: 'Figma Mastery: UI/UX Design from Zero to Hero',
    instructor: 'Sneha Iyer',
    domain: 'design',
    domainLabel: 'UI/UX Design',
    emoji: '🎨',
    level: 'beginner',
    rating: 4.7,
    reviews: 6340,
    students: '48K',
    duration: '28h',
    price: 799,
    originalPrice: 2999,
    badge: 'hot',
    tags: ['Figma', 'Design Systems', 'Prototyping'],
  },
  {
    id: 'c4',
    title: 'Generative AI & LLMs: Engineering Prompt-First Apps',
    instructor: 'Rahul Kapoor',
    domain: 'ai',
    domainLabel: 'AI & ML',
    emoji: '🤖',
    level: 'advanced',
    rating: 4.9,
    reviews: 3820,
    students: '28K',
    duration: '38h',
    price: 1499,
    originalPrice: 5999,
    badge: 'new',
    tags: ['LLMs', 'LangChain', 'RAG', 'GPT-4'],
  },
  {
    id: 'c5',
    title: 'Kubernetes & Docker: Deploy at Scale on AWS',
    instructor: 'Vikram Nair',
    domain: 'devops',
    domainLabel: 'DevOps & Cloud',
    emoji: '☁️',
    level: 'intermediate',
    rating: 4.8,
    reviews: 5100,
    students: '36K',
    duration: '46h',
    price: 1199,
    originalPrice: 4499,
    badge: null,
    tags: ['Kubernetes', 'Docker', 'AWS', 'CI/CD'],
  },
  {
    id: 'c6',
    title: 'Flutter & Dart: Build Cross-Platform Apps',
    instructor: 'Divya Reddy',
    domain: 'mobile',
    domainLabel: 'Mobile Dev',
    emoji: '📱',
    level: 'intermediate',
    rating: 4.6,
    reviews: 4230,
    students: '32K',
    duration: '34h',
    price: 999,
    originalPrice: 3499,
    badge: 'hot',
    tags: ['Flutter', 'Dart', 'Firebase'],
  },
  {
    id: 'c7',
    title: 'System Design Interview: In-Depth Mastery',
    instructor: 'Kiran Bose',
    domain: 'webdev',
    domainLabel: 'Web Dev',
    emoji: '🏗️',
    level: 'advanced',
    rating: 4.9,
    reviews: 8950,
    students: '64K',
    duration: '22h',
    price: 1599,
    originalPrice: 5999,
    badge: 'bestseller',
    tags: ['System Design', 'Microservices', 'Scalability'],
  },
  {
    id: 'c8',
    title: 'SQL + NoSQL Databases: A Complete Developer Guide',
    instructor: 'Ananya Das',
    domain: 'datascience',
    domainLabel: 'Data Science',
    emoji: '🗄️',
    level: 'beginner',
    rating: 4.7,
    reviews: 3670,
    students: '41K',
    duration: '30h',
    price: 0,
    originalPrice: null,
    badge: 'free',
    tags: ['SQL', 'PostgreSQL', 'MongoDB'],
  },
  {
    id: 'c9',
    title: 'Ethical Hacking & Penetration Testing Bootcamp',
    instructor: 'Suresh Kumar',
    domain: 'cybersec',
    domainLabel: 'Cyber Security',
    emoji: '🔐',
    level: 'intermediate',
    rating: 4.8,
    reviews: 4900,
    students: '38K',
    duration: '52h',
    price: 1399,
    originalPrice: 5499,
    badge: 'hot',
    tags: ['Kali Linux', 'Metasploit', 'OWASP'],
  },
  {
    id: 'c10',
    title: 'Product Management: From Idea to Launch',
    instructor: 'Meera Joshi',
    domain: 'business',
    domainLabel: 'Business',
    emoji: '🚀',
    level: 'beginner',
    rating: 4.6,
    reviews: 2890,
    students: '22K',
    duration: '18h',
    price: 699,
    originalPrice: 2499,
    badge: 'new',
    tags: ['Product Strategy', 'Agile', 'Roadmapping'],
  },
  {
    id: 'c11',
    title: 'TypeScript Deep Dive: Advanced Patterns & Architecture',
    instructor: 'Priya Sharma',
    domain: 'webdev',
    domainLabel: 'Web Dev',
    emoji: '🔷',
    level: 'advanced',
    rating: 4.8,
    reviews: 5640,
    students: '44K',
    duration: '24h',
    price: 1099,
    originalPrice: 3999,
    badge: null,
    tags: ['TypeScript', 'Design Patterns', 'Architecture'],
  },
  {
    id: 'c12',
    title: 'Deep Learning with PyTorch & TensorFlow',
    instructor: 'Rahul Kapoor',
    domain: 'ai',
    domainLabel: 'AI & ML',
    emoji: '🧠',
    level: 'advanced',
    rating: 4.9,
    reviews: 7210,
    students: '52K',
    duration: '60h',
    price: 1799,
    originalPrice: 6999,
    badge: 'bestseller',
    tags: ['PyTorch', 'TensorFlow', 'CNNs', 'Transformers'],
  },
];

// ═══════════════════════════════════════════════════════
// COURSE HIERARCHY (for sidebar tree)
// ═══════════════════════════════════════════════════════
const COURSE_TREE = [
  {
    id: 'webdev', label: 'Web Development', emoji: '🌐', count: 248,
    children: [
      { id: 'frontend',     label: 'Frontend',           count: 98  },
      { id: 'backend',      label: 'Backend',            count: 74  },
      { id: 'fullstack',    label: 'Full Stack',         count: 48  },
      { id: 'sysdesign',    label: 'System Design',      count: 28  },
    ],
  },
  {
    id: 'datascience', label: 'Data Science', emoji: '📊', count: 186,
    children: [
      { id: 'python-ds',    label: 'Python & Analytics', count: 64  },
      { id: 'sql-db',       label: 'Databases',          count: 42  },
      { id: 'bi-tools',     label: 'BI & Visualization', count: 38  },
      { id: 'stats',        label: 'Statistics',         count: 42  },
    ],
  },
  {
    id: 'ai', label: 'AI & Machine Learning', emoji: '🤖', count: 164,
    children: [
      { id: 'deep-learning',label: 'Deep Learning',      count: 52  },
      { id: 'nlp',          label: 'NLP',                count: 44  },
      { id: 'gen-ai',       label: 'Generative AI',      count: 38  },
      { id: 'mlops',        label: 'MLOps',              count: 30  },
    ],
  },
  {
    id: 'design', label: 'UI/UX Design', emoji: '🎨', count: 134,
    children: [
      { id: 'figma',        label: 'Figma',              count: 56  },
      { id: 'ux-research',  label: 'UX Research',        count: 38  },
      { id: 'motion',       label: 'Motion Design',      count: 40  },
    ],
  },
  {
    id: 'mobile', label: 'Mobile Development', emoji: '📱', count: 112,
    children: [
      { id: 'flutter',      label: 'Flutter',            count: 46  },
      { id: 'react-native', label: 'React Native',       count: 38  },
      { id: 'ios-swift',    label: 'iOS / Swift',        count: 28  },
    ],
  },
  {
    id: 'devops', label: 'DevOps & Cloud', emoji: '☁️', count: 98,
    children: [
      { id: 'docker-k8s',   label: 'Docker & Kubernetes',count: 42  },
      { id: 'aws',          label: 'AWS',                count: 32  },
      { id: 'cicd',         label: 'CI/CD Pipelines',    count: 24  },
    ],
  },
  {
    id: 'cybersec', label: 'Cyber Security', emoji: '🔐', count: 76,
    children: [
      { id: 'ethical-hack', label: 'Ethical Hacking',    count: 34  },
      { id: 'network-sec',  label: 'Network Security',   count: 24  },
      { id: 'cloud-sec',    label: 'Cloud Security',     count: 18  },
    ],
  },
  {
    id: 'business', label: 'Business & Leadership', emoji: '💼', count: 89,
    children: [
      { id: 'product-mgmt', label: 'Product Management', count: 32  },
      { id: 'startup',      label: 'Startup & Growth',   count: 28  },
      { id: 'finance',      label: 'Finance Basics',     count: 29  },
    ],
  },
];

// ═══════════════════════════════════════════════════════
// LIVE SESSIONS
// ═══════════════════════════════════════════════════════
const LIVE_SESSIONS = [
  {
    id: 'ls1',
    title: 'System Design: Designing Twitter/X at Scale',
    instructor: 'Kiran Bose',
    instructorInitial: 'KB',
    topic: 'webdev',
    topicLabel: 'System Design',
    level: 'advanced',
    status: 'live',
    startTime: 'Live now',
    duration: '90 min',
    viewers: 342,
    enrolled: 1240,
    tags: ['System Design', 'Microservices', 'CAP Theorem'],
    overview: 'In this session, Kiran breaks down how Twitter handles 500M+ tweets per day. We will cover timeline generation with fanout, sharding strategies for the tweet database, real-time event streaming with Kafka, and CDN strategies for media delivery.',
    topics: [
      'Fanout-on-write vs fanout-on-read for timelines',
      'Database sharding & consistent hashing',
      'Redis cache layer for hot timelines',
      'Kafka event streaming for notifications',
      'Global CDN for media at scale',
    ],
    insights: [
      'Twitter uses a hybrid fanout model — precomputed for celebrities, on-demand for regular users.',
      'Read replicas and write-ahead logging are critical for consistency guarantees.',
      'The tweet ID itself encodes a timestamp, shard ID, and sequence number.',
    ],
  },
  {
    id: 'ls2',
    title: 'LangChain + RAG: Build a Production PDF QnA Bot',
    instructor: 'Rahul Kapoor',
    instructorInitial: 'RK',
    topic: 'ai',
    topicLabel: 'Generative AI',
    level: 'intermediate',
    status: 'live',
    startTime: 'Live now',
    duration: '120 min',
    viewers: 218,
    enrolled: 890,
    tags: ['LangChain', 'RAG', 'ChromaDB', 'OpenAI'],
    overview: 'Rahul demonstrates how to build a production-grade RAG (Retrieval-Augmented Generation) pipeline that can answer questions from a collection of uploaded PDFs. The session covers chunking strategies, vector embeddings, retrieval ranking, and deploying with FastAPI.',
    topics: [
      'Document ingestion & text chunking strategies',
      'Generating embeddings with OpenAI Ada-002',
      'Vector store with ChromaDB (local & hosted)',
      'Chain-of-thought retrieval prompting',
      'Deploying the API with FastAPI + Docker',
    ],
    insights: [
      'Chunk size significantly affects retrieval quality — 512 tokens with 50-token overlap is a solid baseline.',
      'HyDE (Hypothetical Document Embeddings) can improve retrieval recall by 30%.',
      'Always add a re-ranker step to combine BM25 sparse retrieval with dense embeddings.',
    ],
  },
  {
    id: 'ls3',
    title: 'React 19 Deep Dive: Server Components & Actions',
    instructor: 'Priya Sharma',
    instructorInitial: 'PS',
    topic: 'webdev',
    topicLabel: 'Frontend',
    level: 'intermediate',
    status: 'upcoming',
    startTime: 'Today 7:00 PM',
    duration: '75 min',
    viewers: 0,
    enrolled: 1640,
    tags: ['React 19', 'Server Components', 'Next.js 15'],
    overview: 'Priya walks through the new mental model introduced in React 19 — server components, server actions, and the transition from client-centric to server-centric rendering. Explore how Next.js 15 App Router leverages these primitives for blazing-fast apps.',
    topics: [
      'Server Components vs Client Components — the mental model',
      'Server Actions: form mutations without API routes',
      'Streaming and Suspense for progressive rendering',
      'Caching strategies in Next.js 15',
      'Migration path from React 18 apps',
    ],
    insights: [
      'Server components run only on the server — they can never be interactive, but they reduce bundle size dramatically.',
      'Forms can call server actions directly with the `action` prop — no fetch() required.',
      'The new `use` hook unlocks reading promises and context in a unified API.',
    ],
  },
  {
    id: 'ls4',
    title: 'Flutter Animations: Lottie, Hero & Custom Painters',
    instructor: 'Divya Reddy',
    instructorInitial: 'DR',
    topic: 'mobile',
    topicLabel: 'Mobile Dev',
    level: 'intermediate',
    status: 'upcoming',
    startTime: 'Today 9:00 PM',
    duration: '60 min',
    viewers: 0,
    enrolled: 520,
    tags: ['Flutter', 'Animations', 'CustomPainter', 'Lottie'],
    overview: 'Divya demonstrates three levels of Flutter animations — declarative Hero transitions, the Lottie JSON ecosystem for vector animations, and low-level CustomPainter for pixel-perfect effects. Live coding throughout with a real portfolio app.',
    topics: [
      'Implicit vs explicit animations in Flutter',
      'Hero & page route transitions',
      'Integrating Lottie for JSON-based animations',
      'CustomPainter & Canvas API deep dive',
      'Performance profiling: jank detection',
    ],
    insights: [
      'Use `RepaintBoundary` strategically to isolate heavy animation widgets and prevent repaints.',
      'Lottie files can be 95% smaller than equivalent GIFs — ideal for mobile.',
      'The `Ticker` class is the heartbeat of all Flutter animations.',
    ],
  },
  {
    id: 'ls5',
    title: 'Kubernetes Troubleshooting Workshop: Real Production Incidents',
    instructor: 'Vikram Nair',
    instructorInitial: 'VN',
    topic: 'devops',
    topicLabel: 'DevOps & Cloud',
    level: 'advanced',
    status: 'upcoming',
    startTime: 'Tomorrow 11:00 AM',
    duration: '90 min',
    viewers: 0,
    enrolled: 740,
    tags: ['Kubernetes', 'Debugging', 'Observability', 'Helm'],
    overview: 'Vikram replays five real Kubernetes production incidents and walks through the exact kubectl commands, log analysis, and Prometheus queries used to diagnose and resolve each. From CrashLoopBackOff to resource starvation to networking misconfigurations.',
    topics: [
      'CrashLoopBackOff: common causes & remedies',
      'OOMKilled: tuning memory limits with VPA',
      'Pod pending: taints, tolerations & node affinity',
      'DNS resolution failures in multi-namespace setups',
      'Prometheus + Grafana dashboards for incident response',
    ],
    insights: [
      '80% of K8s production issues trace back to misconfigured resource requests/limits.',
      'Always set `liveness` and `readiness` probes — pods without them cause silent traffic failures.',
      'Use `kubectl debug` (ephemeral containers) for distroless images you can\'t exec into.',
    ],
  },
  {
    id: 'ls6',
    title: 'Data Visualization with Plotly & Dash: Interactive Dashboards',
    instructor: 'Ananya Das',
    instructorInitial: 'AD',
    topic: 'datascience',
    topicLabel: 'Data Science',
    level: 'beginner',
    status: 'upcoming',
    startTime: 'Tomorrow 6:00 PM',
    duration: '75 min',
    viewers: 0,
    enrolled: 680,
    tags: ['Plotly', 'Dash', 'Python', 'Data Viz'],
    overview: 'Ananya builds a complete real-time analytics dashboard from scratch using Plotly Express and Dash. The session covers layout composition, callbacks for interactivity, live data updates, and deploying the finished app to Heroku in under 10 minutes.',
    topics: [
      'Plotly Express vs Graph Objects — when to use what',
      'Dash layout: HTML & core components',
      'Callbacks: linking inputs to chart outputs',
      'Interval component for live polling',
      'One-click deploy to Heroku',
    ],
    insights: [
      'Plotly is the only Python viz library that outputs interactive HTML natively — no JavaScript needed.',
      'Use `dcc.Store` to share state between callbacks without global variables.',
      'For large datasets, reduce data on the server side via Pandas aggregation before sending to the browser.',
    ],
  },
];

// ═══════════════════════════════════════════════════════
// TICKER ITEMS
// ═══════════════════════════════════════════════════════
const TICKER_ITEMS = [
  { text: 'React 19 Server Components — New Session Added', tag: 'New' },
  { text: '10K+ enrolled in Python ML Bootcamp this week', tag: 'Trending' },
  { text: 'System Design sold out — next batch 24 Apr', tag: 'Alert' },
  { text: 'Free SQL + MongoDB course now live', tag: 'Free' },
  { text: 'LangChain RAG workshop → 218 watching right now', tag: 'Live' },
  { text: 'New: Generative AI & LLM Engineering track', tag: 'New' },
  { text: 'Flutter Animations session — Today 9 PM IST', tag: 'Upcoming' },
  { text: 'Congratulations to 50,000 certificate earners in March!', tag: '🎉' },
  { text: 'Kubernetes Troubleshooting — 740 registered', tag: 'Upcoming' },
  { text: 'Plotly + Dash: Tomorrow 6 PM — limited seats', tag: 'Soon' },
];

// ═══════════════════════════════════════════════════════
// CONTINUE LEARNING (user's in-progress courses)
// ═══════════════════════════════════════════════════════
const CONTINUE_COURSES = [
  { id: 'c1',  emoji: '⚛️', title: 'React 19 & Next.js 15',            instructor: 'Priya Sharma',  progress: 68 },
  { id: 'c4',  emoji: '🤖', title: 'Generative AI & LLMs',             instructor: 'Rahul Kapoor',  progress: 32 },
  { id: 'c5',  emoji: '☁️',  title: 'Kubernetes & Docker on AWS',       instructor: 'Vikram Nair',   progress: 15 },
];

// ═══════════════════════════════════════════════════════
// SEARCH INDEX
// ═══════════════════════════════════════════════════════
const SEARCH_INDEX = [
  ...COURSES.map(c => ({
    type: 'course',
    id: c.id,
    title: c.title,
    sub: `${c.instructor} · ${c.domainLabel}`,
    emoji: c.emoji,
    page: 'courses',
  })),
  ...LIVE_SESSIONS.map(s => ({
    type: 'live',
    id: s.id,
    title: s.title,
    sub: `${s.instructor} · ${s.status === 'live' ? '🔴 Live Now' : s.startTime}`,
    emoji: s.instructorInitial,
    page: 'live',
  })),
  ...DOMAINS.map(d => ({
    type: 'domain',
    id: d.id,
    title: d.name,
    sub: `${d.count} courses`,
    emoji: d.emoji,
    page: 'courses',
  })),
];

// ═══════════════════════════════════════════════════════
// CERTIFICATES
// ═══════════════════════════════════════════════════════
const CERTIFICATES = [
  {
    id: 'cert1',
    emoji: '⚛️',
    title: 'React Advanced Patterns & Architecture',
    instructor: 'Priya Sharma · LearnFlow',
    date: 'Issued 14 March 2026',
    credentialId: 'LF-REACT-2026-84921',
  },
  {
    id: 'cert2',
    emoji: '📊',
    title: 'Python for Data Science — Complete Bootcamp',
    instructor: 'Arjun Mehta · LearnFlow',
    date: 'Issued 2 January 2026',
    credentialId: 'LF-PDS-2026-31077',
  },
];
